//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace Useful {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class UsefulConfig {
        
        private string schemaPathField;
        
        private UsefulConfigConsumer[] consumersField;
        
        private UsefulConfigLetter[] lettersField;
        
        /// <remarks/>
        public string SchemaPath {
            get {
                return this.schemaPathField;
            }
            set {
                this.schemaPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Consumer", IsNullable=false)]
        public UsefulConfigConsumer[] Consumers {
            get {
                return this.consumersField;
            }
            set {
                this.consumersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Letter", IsNullable=false)]
        public UsefulConfigLetter[] Letters {
            get {
                return this.lettersField;
            }
            set {
                this.lettersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class UsefulConfigConsumer {
        
        private UsefulConfigConsumerDataService dataServiceField;
        
        private string cultureField;
        
        private string nameField;
        
        /// <remarks/>
        public UsefulConfigConsumerDataService DataService {
            get {
                return this.dataServiceField;
            }
            set {
                this.dataServiceField = value;
            }
        }
        
        /// <remarks/>
        public string Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class UsefulConfigConsumerDataService {
        
        private UsefulConfigConsumerDataServiceFile fileField;
        
        private UsefulConfigConsumerDataServiceQueue queueField;
        
        private UsefulConfigConsumerDataServiceTransport transportField;
        
        /// <remarks/>
        public UsefulConfigConsumerDataServiceFile File {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        public UsefulConfigConsumerDataServiceQueue Queue {
            get {
                return this.queueField;
            }
            set {
                this.queueField = value;
            }
        }
        
        /// <remarks/>
        public UsefulConfigConsumerDataServiceTransport Transport {
            get {
                return this.transportField;
            }
            set {
                this.transportField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class UsefulConfigConsumerDataServiceFile {
        
        private string pathField;
        
        private bool deleteField;
        
        private string filterField;
        
        private byte timeoutField;
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public bool Delete {
            get {
                return this.deleteField;
            }
            set {
                this.deleteField = value;
            }
        }
        
        /// <remarks/>
        public string Filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
            }
        }
        
        /// <remarks/>
        public byte Timeout {
            get {
                return this.timeoutField;
            }
            set {
                this.timeoutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class UsefulConfigConsumerDataServiceQueue {
        
        private string inboxField;
        
        private string outboxField;
        
        private string successField;
        
        private string failField;
        
        /// <remarks/>
        public string Inbox {
            get {
                return this.inboxField;
            }
            set {
                this.inboxField = value;
            }
        }
        
        /// <remarks/>
        public string Outbox {
            get {
                return this.outboxField;
            }
            set {
                this.outboxField = value;
            }
        }
        
        /// <remarks/>
        public string Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string Fail {
            get {
                return this.failField;
            }
            set {
                this.failField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class UsefulConfigConsumerDataServiceTransport {
        
        private Transport outField;
        
        private Transport successField;
        
        private Transport failField;
        
        /// <remarks/>
        public Transport Out {
            get {
                return this.outField;
            }
            set {
                this.outField = value;
            }
        }
        
        /// <remarks/>
        public Transport Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public Transport Fail {
            get {
                return this.failField;
            }
            set {
                this.failField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    public enum Transport {
        
        /// <remarks/>
        File,
        
        /// <remarks/>
        Queue,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class UsefulConfigLetter {
        
        private string nameField;
        
        private float frequencyField;
        
        private bool frequencyFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FrequencySpecified {
            get {
                return this.frequencyFieldSpecified;
            }
            set {
                this.frequencyFieldSpecified = value;
            }
        }
    }
}
