//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Useful
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Useful.Useful.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 64 bit.
        /// </summary>
        internal static string _64bit
        {
            get
            {
                return ResourceManager.GetString("_64bit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Argument{0} = {1}.
        /// </summary>
        internal static string ArgumentNameValue
        {
            get
            {
                return ResourceManager.GetString("ArgumentNameValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Available Rotors.
        /// </summary>
        internal static string AvailableRotors
        {
            get
            {
                return ResourceManager.GetString("AvailableRotors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string Browse
        {
            get
            {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cipher.
        /// </summary>
        internal static string Cipher
        {
            get
            {
                return ResourceManager.GetString("Cipher", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ciphers.
        /// </summary>
        internal static string Ciphers
        {
            get
            {
                return ResourceManager.GetString("Ciphers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ciphertext.
        /// </summary>
        internal static string CipherText
        {
            get
            {
                return ResourceManager.GetString("CipherText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close
        {
            get
            {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .NET Version.
        /// </summary>
        internal static string ClrVersion
        {
            get
            {
                return ResourceManager.GetString("ClrVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Command line = {0}.
        /// </summary>
        internal static string CommandLine
        {
            get
            {
                return ResourceManager.GetString("CommandLine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error reading from config..
        /// </summary>
        internal static string ConfigReadError
        {
            get
            {
                return ResourceManager.GetString("ConfigReadError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Application configuration system error..
        /// </summary>
        internal static string ConfigSysError
        {
            get
            {
                return ResourceManager.GetString("ConfigSysError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A Cryptographic error occurred: {0}.
        /// </summary>
        internal static string CryptoError
        {
            get
            {
                return ResourceManager.GetString("CryptoError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cryptography.
        /// </summary>
        internal static string Cryptography
        {
            get
            {
                return ResourceManager.GetString("Cryptography", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decipher.
        /// </summary>
        internal static string Decipher
        {
            get
            {
                return ResourceManager.GetString("Decipher", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decryption complete..
        /// </summary>
        internal static string DecryptionComplete
        {
            get
            {
                return ResourceManager.GetString("DecryptionComplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encipher.
        /// </summary>
        internal static string Encipher
        {
            get
            {
                return ResourceManager.GetString("Encipher", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encryption complete..
        /// </summary>
        internal static string EncryptionComplete
        {
            get
            {
                return ResourceManager.GetString("EncryptionComplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string Environment
        {
            get
            {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File
        {
            get
            {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A file error occurred: {0}.
        /// </summary>
        internal static string FileError
        {
            get
            {
                return ResourceManager.GetString("FileError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string Finished
        {
            get
            {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Free Text.
        /// </summary>
        internal static string FreeText
        {
            get
            {
                return ResourceManager.GetString("FreeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alpha.
        /// </summary>
        internal static string Greek_Alpha
        {
            get
            {
                return ResourceManager.GetString("Greek_Alpha", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Beta.
        /// </summary>
        internal static string Greek_Beta
        {
            get
            {
                return ResourceManager.GetString("Greek_Beta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gamma.
        /// </summary>
        internal static string Greek_Gamma
        {
            get
            {
                return ResourceManager.GetString("Greek_Gamma", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hawky_128_4
        {
            get
            {
                object obj = ResourceManager.GetObject("Hawky_128_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hawky_all
        {
            get
            {
                object obj = ResourceManager.GetObject("hawky_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input buffer not long enough..
        /// </summary>
        internal static string InputBufferLength
        {
            get
            {
                return ResourceManager.GetString("InputBufferLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input file.
        /// </summary>
        internal static string InputFile
        {
            get
            {
                return ResourceManager.GetString("InputFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        internal static string Machine
        {
            get
            {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The method or operation is not implemented..
        /// </summary>
        internal static string MethodNotImplemented
        {
            get
            {
                return ResourceManager.GetString("MethodNotImplemented", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configuration directory does not exist..
        /// </summary>
        internal static string NoConfigDir
        {
            get
            {
                return ResourceManager.GetString("NoConfigDir", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configuration file does not exist..
        /// </summary>
        internal static string NoConfigFile
        {
            get
            {
                return ResourceManager.GetString("NoConfigFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No configuration path specified..
        /// </summary>
        internal static string NoConfigPath
        {
            get
            {
                return ResourceManager.GetString("NoConfigPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configuration schema file does not exist..
        /// </summary>
        internal static string NoConfigSchema
        {
            get
            {
                return ResourceManager.GetString("NoConfigSchema", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None
        {
            get
            {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Number out of allowed values..
        /// </summary>
        internal static string NumberOutOfRangeMessage
        {
            get
            {
                return ResourceManager.GetString("NumberOutOfRangeMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OS.
        /// </summary>
        internal static string OperatingSystem
        {
            get
            {
                return ResourceManager.GetString("OperatingSystem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OS Type.
        /// </summary>
        internal static string OperatingSystemType
        {
            get
            {
                return ResourceManager.GetString("OperatingSystemType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output encoding.
        /// </summary>
        internal static string OutputEncoding
        {
            get
            {
                return ResourceManager.GetString("OutputEncoding", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output file.
        /// </summary>
        internal static string OutputFile
        {
            get
            {
                return ResourceManager.GetString("OutputFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Plaintext.
        /// </summary>
        internal static string PlainText
        {
            get
            {
                return ResourceManager.GetString("PlainText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Plugboard.
        /// </summary>
        internal static string Plugboard
        {
            get
            {
                return ResourceManager.GetString("Plugboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position
        {
            get
            {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Process Type.
        /// </summary>
        internal static string ProcessType
        {
            get
            {
                return ResourceManager.GetString("ProcessType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string QuestionMark
        {
            get
            {
                return ResourceManager.GetString("QuestionMark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Randomize.
        /// </summary>
        internal static string Randomize
        {
            get
            {
                return ResourceManager.GetString("Randomize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        internal static string RomanNumeral_1
        {
            get
            {
                return ResourceManager.GetString("RomanNumeral_1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to II.
        /// </summary>
        internal static string RomanNumeral_2
        {
            get
            {
                return ResourceManager.GetString("RomanNumeral_2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to III.
        /// </summary>
        internal static string RomanNumeral_3
        {
            get
            {
                return ResourceManager.GetString("RomanNumeral_3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IV.
        /// </summary>
        internal static string RomanNumeral_4
        {
            get
            {
                return ResourceManager.GetString("RomanNumeral_4", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        internal static string RomanNumeral_5
        {
            get
            {
                return ResourceManager.GetString("RomanNumeral_5", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VI.
        /// </summary>
        internal static string RomanNumeral_6
        {
            get
            {
                return ResourceManager.GetString("RomanNumeral_6", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VII.
        /// </summary>
        internal static string RomanNumeral_7
        {
            get
            {
                return ResourceManager.GetString("RomanNumeral_7", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VIII.
        /// </summary>
        internal static string RomanNumeral_8
        {
            get
            {
                return ResourceManager.GetString("RomanNumeral_8", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rotor Number.
        /// </summary>
        internal static string RotorNumber
        {
            get
            {
                return ResourceManager.GetString("RotorNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rotor Position.
        /// </summary>
        internal static string RotorPosition
        {
            get
            {
                return ResourceManager.GetString("RotorPosition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown dimension..
        /// </summary>
        internal static string UnknownDimension
        {
            get
            {
                return ResourceManager.GetString("UnknownDimension", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown name..
        /// </summary>
        internal static string UnknownName
        {
            get
            {
                return ResourceManager.GetString("UnknownName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown symbol..
        /// </summary>
        internal static string UnknownSymbol
        {
            get
            {
                return ResourceManager.GetString("UnknownSymbol", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown unit..
        /// </summary>
        internal static string UnknownUnit
        {
            get
            {
                return ResourceManager.GetString("UnknownUnit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unsupported transform mode..
        /// </summary>
        internal static string UnsupportedTransformMode
        {
            get
            {
                return ResourceManager.GetString("UnsupportedTransformMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Useful Data Service.
        /// </summary>
        internal static string UsefulDataService
        {
            get
            {
                return ResourceManager.GetString("UsefulDataService", resourceCulture);
            }
        }
    }
}