//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50215.44
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Useful.DataServices.Console.Properties.Settings.get_Default():Useful.DataServices" +
    ".Console.Properties.Settings")]

namespace Useful.DataServices.Console.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = new Settings();
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/UsefulWeb/DataService.asmx")]
        public string Useful_DataServices_Console_DataService_Useful_x0020_Data_x0020_Services_x0020_Web_x0020_Service {
            get {
                return ((string)(this["Useful_DataServices_Console_DataService_Useful_x0020_Data_x0020_Services_x0020_We" +
                    "b_x0020_Service"]));
            }
        }
    }
}
